name: CD Deploy Cloud Run Job


on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GOOGLE_PROJECT }}
      REGION: us-central1
      IMAGE_REPOSITORY: imagen
      IMAGE_NAME: vertex_pipeline

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true


      - name: build and push artifact registry
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/$IMAGE_REPOSITORY/$IMAGE_NAME:latest ./despliegue_cloud_run
          docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/$IMAGE_REPOSITORY/$IMAGE_NAME:latest



      - name: Deploy Cloud Run Job
        run: |
          gcloud run jobs deploy run-pipeline-job \
            --image us-central1-docker.pkg.dev/$PROJECT_ID/$IMAGE_REPOSITORY/$IMAGE_NAME \
            --region $REGION \
            --service-account cloud-run-job@$PROJECT_ID.iam.gserviceaccount.com \
            --set-env-vars PROJECT_ID=mlops16,LOCATION=us-central1,PIPELINE_PATH=gs://mlops16/marketing/clustering_model/pipeline_prediction/pipeline_bigquery.json,SERVICE_ACCOUNT=vertex-procesing@mlops16.iam.gserviceaccount.com,VALIDA_TABLE=mlops16.github_mlops.census_by_age,INPUT_AGE=60 \
            --quiet

